name: SearchGame
options:
  bundleIdPrefix: com.searchgame
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

targets:
  SearchGame:
    type: application
    platform: iOS
    sources:
      - path: SearchGame
        excludes:
          - "**/*.xcassets"
      - path: SearchGame/Resources/Assets.xcassets
        type: folder
      - path: SearchGame/Resources/Generated
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.searchgame.app
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: Search Game
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        INFOPLIST_KEY_UIRequiresFullScreen: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies: []

  SearchGameTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SearchGameTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.searchgame.tests
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: SearchGame

  SearchGameUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SearchGameUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.searchgame.uitests
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: SearchGame

schemes:
  SearchGame:
    build:
      targets:
        SearchGame: all
        SearchGameTests: [test]
        SearchGameUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SearchGameTests
        - SearchGameUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
